autoDetectedPackages:
- com.fangyang.demo.utils
- com.fangyang.java8
- com.fangyang.java9
- com.hashmap
- java17_new_features.src.test.java
- java8_new_features.src.main.java
- java8_new_features.src.test.java
- java9_new_features.src.main.java
- java9_new_features.src.test.java
- java9_new_features_test.src.main.java
enableAutoDetect: true
entryDisplayConfig:
  excludedPathPatterns: []
  skipJsCss: true
funcDisplayConfig:
  skipConstructors: false
  skipFieldAccess: true
  skipFieldChange: true
  skipGetters: true
  skipNonProjectPackages: true
  skipPrivateMethods: false
  skipSetters: true
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
recordMode: smart
sourceDisplayConfig:
  color: blue
startOnDebug: false
